FROM gliderlabs/alpine:3.1
VOLUME /mnt/routes
EXPOSE 8000

ENV GOPATH /go
RUN apk-install go git mercurial
COPY . /go/src/github.com/fabric8io/kadvisor
WORKDIR /go/src/github.com/fabric8io/kadvisor
CMD export GOPATH=/go \
  && export PATH=$GOPATH/bin:$PATH \
  && go get github.com/tools/godep \
  && godep go build -ldflags "-X main.Version dev" -o /bin/kadvisor \
  && exec /bin/kadvisor
